backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "pages"
    label: "Pages"
    label_singular: 'Page' # Used in the UI, ie: "New Post"
    folder: 'blog'
    create: true
    files:
    - label: "Home"
      name: "home"
      file: "content/blog/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
  - name: "photos"
    label: "Photos"
    files:
    - label: "Home"
      name: "home"
      file: "content/blog/photo.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
